redis:
    image: redis:2
    ports:
        - "6379"
    # expose db in the host /data dir, make sure to create and set permissions for this folder
    volumes:
        - /data:/data
watchmenpopulate:
    # populates with stub data of real services
    build: ./
    links:
        - redis
    command: node scripts/data-load/populate-services-from-fixtures.js -r -e production
    env_file: docker-compose.env
watchmenweb:
    build: ./
    ports:
        - "3000:3000"
    links:
        - redis
    command: node run-web-server.js
    env_file: docker-compose.env
watchmenserver:
    build: ./
    links:
        - redis
    command: node run-monitor-server.js
    env_file: docker-compose.env
